#!/usr/bin/env python3
"""
batch_apply.py — Apply mount-spam pod manifests in fixed-size batches,
waiting for each batch to settle before applying the next.

Reads manifests/ns{0..N-1}_pods.yaml (each a multi-doc YAML of Pod objects,
as generated by setup_workload.sh's gen_mount_workload.py step) and applies
all pods across all namespaces in batches of BATCH_SIZE, interleaved evenly.

Usage:
  KUBECONFIG=... python3 batch_apply.py [--batch-size 100] [--namespaces 10] \
      [--settle-timeout 120] [--settle-poll 5]
"""
import argparse
import glob
import os
import subprocess
import sys
import time

import yaml


def kube_env(kubeconfig):
    env = os.environ.copy()
    env["KUBECONFIG"] = kubeconfig
    return env


def load_pods(manifest_dir, namespaces):
    pods = []
    for i in range(namespaces):
        path = f"{manifest_dir}/ns{i}_pods.yaml"
        with open(path) as f:
            docs = [d for d in yaml.safe_load_all(f) if d]
        pods.extend(docs)
    return pods


def apply_batch(docs, kubeconfig):
    manifest = "\n---\n".join(yaml.safe_dump(d) for d in docs)
    p = subprocess.run(
        ["kubectl", "apply", "-f", "-"],
        input=manifest,
        text=True,
        capture_output=True,
        env=kube_env(kubeconfig),
    )
    if p.returncode != 0:
        print(f"  ERROR applying batch: {p.stderr}", file=sys.stderr)
    return p.returncode == 0


def get_pod_status_counts(kubeconfig):
    p = subprocess.run(
        ["kubectl", "get", "pods", "-A", "-l", "app=mount-spam", "--no-headers"],
        text=True,
        capture_output=True,
        env=kube_env(kubeconfig),
    )
    counts = {}
    for line in p.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 4:
            phase = parts[3]
            counts[phase] = counts.get(phase, 0) + 1
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--batch-size", type=int, default=100)
    ap.add_argument("--namespaces", type=int, default=10)
    ap.add_argument("--manifest-dir", default="manifests")
    ap.add_argument("--settle-timeout", type=int, default=120,
                     help="max seconds to wait per batch for pods to leave Pending/ContainerCreating")
    ap.add_argument("--settle-poll", type=int, default=5)
    ap.add_argument("--kubeconfig", required=True)
    args = ap.parse_args()

    pods = load_pods(args.manifest_dir, args.namespaces)
    total = len(pods)
    print(f"Loaded {total} pod manifests across {args.namespaces} namespaces.", flush=True)
    print(f"Applying in batches of {args.batch_size}.", flush=True)

    applied = 0
    batch_num = 0
    while applied < total:
        batch = pods[applied: applied + args.batch_size]
        batch_num += 1
        print(f"\n=== Batch {batch_num}: applying pods {applied}..{applied + len(batch) - 1} ({len(batch)} pods) ===")
        ok = apply_batch(batch, args.kubeconfig)
        applied += len(batch)
        if not ok:
            print("  Batch apply reported errors, continuing anyway.")

        # Settle: wait until this batch's pods leave Pending/ContainerCreating,
        # or until settle-timeout elapses, whichever comes first.
        deadline = time.time() + args.settle_timeout
        while time.time() < deadline:
            counts = get_pod_status_counts(args.kubeconfig)
            running = counts.get("Running", 0)
            pending = counts.get("Pending", 0)
            creating = counts.get("ContainerCreating", 0)
            print(f"  [{int(deadline - time.time())}s left] Running={running} Pending={pending} ContainerCreating={creating} (cumulative applied={applied})")
            if pending == 0 and creating <= max(5, args.batch_size // 10):
                print("  Batch settled.")
                break
            time.sleep(args.settle_poll)
        else:
            print("  Settle timeout reached, proceeding to next batch anyway.")

    print(f"\n=== All {total} pods applied across {batch_num} batches ===")


if __name__ == "__main__":
    main()
